import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const PAGES = [
  { title: "about", path: "/about", describtion: "Видео иструкции по пользованию приложением" },
  { title: "contact", path: "/contact", describtion: "Cвяжитесь с нами" },
  { title: "auth", path: "/auth/login", describtion: "Регистрация" },
  { title: "support us", path: "/support", describtion: "Возможность поблагодарить" },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
            <a
              href="https://play.google.com/store/apps/details?id=com.company.infocars&hl=en-US&ah=Td2Q3nYBQV7iJk8lD8JSCJVtpzQp"
              target="_blank"
              rel="noopener noreferrer"
            >
              скачать версию для Анроид{" "}
              <Image src="/logo.png" alt="Info cars Android Logo" className={styles.vercelLogo} width={50} height={24} priority />{" "}
            </a>
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              скачать версию для IOS
              <Image src="/logo.png" alt="Info cars Android Logo" className={styles.vercelLogo} width={50} height={24} priority />
            </a>
          </div>
        </div>

        <div className={styles.homeImg} />

        <div className={styles.grid}>
          {PAGES.map((page) => (
            <Link href={page.path}>
              <h2>{page.title}</h2>
              <p>{page.describtion}</p>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
